"""empty message

Revision ID: b9b292f621ca
Revises: 
Create Date: 2020-04-22 17:17:50.509720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9b292f621ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.String(), autoincrement=False, nullable=False),
    sa.Column('target_weight', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('progress',
    sa.Column('user_id', sa.String(), autoincrement=False, nullable=False),
    sa.Column('track_date', sa.DateTime(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('mood', sa.String(), nullable=False),
    sa.Column('diet', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'track_date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('progress')
    op.drop_table('user')
    # ### end Alembic commands ###
